name: Get YouTube Video Info

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Video URL'
        required: true

jobs:
  get_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      # (Optionnel) cookies pour vidéos restreintes
      - name: Prepare cookies (optional)
        if: ${{ secrets.COOKIES_B64 != '' }}
        run: |
          echo "${{ secrets.COOKIES_B64 }}" | base64 -d > cookies.txt

      - name: Prepare output filename
        id: prep
        run: |
          url="${{ github.event.inputs.video_url }}"
          slug=$(echo "$url" | sed 's/[^a-zA-Z0-9]/_/g')
          ts=$(date +%s)
          mkdir -p outputs
          echo "FILENAME=outputs/video_info_${ts}_${slug}.json" >> $GITHUB_ENV
          echo "filename=outputs/video_info_${ts}_${slug}.json" >> $GITHUB_OUTPUT

      - name: Run extractor (yt-dlp + transcript)
        env:
          YT_URL: ${{ github.event.inputs.video_url }}
        run: |
          if [ -f cookies.txt ]; then
            python main.py "$YT_URL" "${{ env.FILENAME }}" --cookies cookies.txt
          else
            python main.py "$YT_URL" "${{ env.FILENAME }}"
          fi

      - name: Commit result JSON
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "${{ env.FILENAME }}"
          git commit -m "Add video info: ${{ env.FILENAME }}" || echo "Nothing to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
